### PR TITLE
Refactoring data and examples

### PR DESCRIPTION
**Pull request by jucordero**
This PR removes the `examples` and `reading_data` notebooks, which will be moved to new repositories for clarity purposes.

https://github.com/FixOurFood/agrifoodpy-examples
https://github.com/FixOurFood/agrifoodpy-data

It also removes some old files no longer needed.
After this PR is reviewed and closed, BFG should be run on the repository to clean all references to removed files and old versions of data files which we don't need to be in the gt history.

### CODE REVIEW

**Comment by jucordero** [comment]
@kaedonkers

**Comment by sarahbridle** [comment]
Looks great to me! Ideal if @kaedonkers would check if this ticks the boxes.

**Comment by kaedonkers** [comment]
Really sorry on the radio silence - been starting a placement this week which has taken up a lot of my time. Will look at this in the next three days

**Comment by jucordero** [comment]
`agrifoodpy-data` would contain the notebooks and scripts necessary to generate the data that will reside in the main `agrifoodpy` repository. This way we keep this repository cleaner and at the same we have a place to point to where we're asked about how each array file has been generated.

**Pull request closed without merging**
